#! /bin/bash

src="src"
todo_source="$src/todo.sh"
init="$src/init.py"
read_file="$src/read_file.py"
add_todo="$src/add_todo.py"
delete_todo="$src/delete_todo.py"

export src
export todo_source
export init
export read_todo
export add_todo
export delete_todo

file_directory=$(dirname ${BASH_SOURCE[0]})
cd "$file_directory"

function assistant()
{
  action="$1"
  shift

  case "$action" in
    todo)
      (
        . "$todo_source"

        todo "$@"
        return "$?"
      )
      ;;
    *)
      printf "This option is invalid. Please try one of these:\n"
      printf -- "- todo\n"
      return 1
      ;;
  esac
}

python3 "$init"
assistant "$@"
