#! /bin/bash

src="src"
init="$src/init.py"
todo_source="$src/todo.sh"
add_todo="$src/add_todo.py"
read_file="$src/read_file.py"
delete_todo="$src/delete_todo.py"
format_files="$src/format_files.sh"

export src
export init
export todo_source
export read_todo
export add_todo
export delete_todo
export format_files

. "$format_files"

file_directory=$(dirname ${BASH_SOURCE[0]})
cd "$file_directory"

function assistant()
{
  action="$1"
  shift

  case "$action" in
    todo)
      (
        . "$todo_source"

        todo "$@"
        return "$?"
      )
      ;;
    *)
      printf "This option is invalid. Please try one of these:\n"
      printf -- "- todo\n"
      return 1
      ;;
  esac
}

format_files
python3 "$init"
assistant "$@"
